/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FFC03
 */
import classes.News;
import classes.FakeNews;
import classes.RealNews;
import java.io.*;
import java.util.Scanner;
import java.util.ArrayList;
public class setup extends javax.swing.JFrame {
    //Variables to be passed to other forms
    public static ArrayList<News> quiz;
    public static int size;
    public static final int DEFAULT_SIZE = 6;
    
    public setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("The Credible Lens");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("Category");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Animal", "Entertainment", "Health", "Sports" }));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setText("# of questions");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jButton1.setText("Begin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(number))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //A try-catch block to check if the user fails to input an integer number
        try{
            //If the user doesn't specify the number of questions they want, the number inputted is greater than the
            //maximum number of questions in each category, or the number inputted is nonpositive, set size to DEFAULT_SIZE.
            //Otherwise, set size to inputted number.
            if (number.getText().equals("") || Integer.parseInt(number.getText()) > 6
                    || Integer.parseInt(number.getText()) <= 0){
                size = DEFAULT_SIZE;
            } else{
                size = Integer.parseInt(number.getText());
            }
            //Randomize a quiz with specified size and category
            quiz = randomize(size, jComboBox1.getSelectedItem().toString());
            this.setVisible(false);
            new questions().setVisible(true);
        } catch (NumberFormatException e){
            jLabel3.setText("Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setup().setVisible(true);
            }
        });
    }
    
    
    /**
     * This method randomizes a quiz of real news and fake news with specified size and category.
     * @param size
     * @param category
     * @return an ArrayList of News objects
     */
    private static ArrayList<News> randomize(int size, String category){
        //Declare an ArrayList for News objects obtained from the file
        ArrayList<News> news = new ArrayList<News>();
        try{
            //Read from the "News.tsv" file
            Scanner scan = new Scanner(new File("News.tsv"));
            while (scan.hasNextLine()){
                String[] elements = scan.nextLine().split("\t");
                //If the specified category is "All" or the specified category matched the category of the current line,
                //Add the News object to the ArrayList (if the type of the line is real, instantiate as a RealNews object;
                //if the type of the line is fake, instantiate as a FakeNews object).
                if (category.equalsIgnoreCase("All") || elements[1].equalsIgnoreCase(category)){
                    if (elements[0].equals("Real")){
                        news.add(new RealNews(elements[0].trim(), elements[1].trim(), 
                                elements[2].trim(), elements[3].trim(), elements[4].trim(), 
                                elements[5].trim(), elements[6].trim(), elements[7].trim()));
                    } else{
                        news.add(new FakeNews(elements[0].trim(), elements[1].trim(), 
                                elements[2].trim(), elements[3].trim(), elements[4].trim(), 
                                elements[5].trim(), elements[6].trim(), elements[7].trim()));
                    }
                }
            }
            //Declare another ArrayList of News objects for randomized quiz
            ArrayList<News> randomized = new ArrayList<News>();
            //Randomize an index, add the News object of ArrayList news at this index to ArrayList randomized.
            //Remove that object from ArrayList news to avoid replication.
            for (int i = 0; i < size; i ++){
                int index = (int)(Math.random() * news.size());
                randomized.add(news.get(index));
                news.remove(index);
            }
            //Return the randomized quiz
            return randomized;
        } catch (IOException e){
            System.out.println("IOException occured");
            return news;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField number;
    // End of variables declaration//GEN-END:variables
}
